#Apache2 Module to consume to access and error logs from mounted volume
filebeat.inputs:
- type: filestream
  # Change to true to enable this input configuration.
  enabled: true
  paths:
    - "/usr/local/apache2/logs/*"
  #fields:
  #  apache: true
  #fields_under_root: true
#- module: apache2
#  access:
#    var.paths: ["/var/log/apache2/access.log*"]
#  error:
#    var.paths: ["/var/log/apache2/error.log*"]
output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["broker1:29092","broker2:29092","broker3:29092"]

  # message topic selection + partitioning
  topic: "lab8"
#  partition.round_robin:
#    reachable_only: false

#  required_acks: 1
#  compression: gzip
  max_message_bytes: 1000000
